Vagrant.configure("2") do |config|
  config.vm.box = "precise64"

  config.vm.network :forwarded_port, guest: 80, host: 80
  config.vm.network :forwarded_port, guest: 81, host: 81
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 27017, host: 27017

  config.vm.provision :shell do |s|
    s.path = "provision"
  end

  config.vm.synced_folder "../../src", "/vagrant-mnt/src"
  config.vm.synced_folder "../shared", "/vagrant-mnt/env/shared"
  config.vm.synced_folder "../../../ops.bill-boyer.com/", "/vagrant-mnt/ops"
end
