Vagrant.configure("2") do |config|
  config.vm.box = "precise64"

  config.vm.network :forwarded_port, guest: 80, host: 80
  config.vm.network :forwarded_port, guest: 81, host: 8081
  config.vm.network :forwarded_port, guest: 8080, host: 8082
  config.vm.network :forwarded_port, guest: 3000, host: 8300

  config.vm.provision :shell do |s|
    s.path = "provision"
  end

  config.vm.synced_folder "../../src", "/vagrant-mnt/src"
  config.vm.synced_folder "../shared", "/vagrant-mnt/env-shared"
  config.vm.synced_folder "../../../ops.bill-boyer.com/", "/vagrant-mnt/ops"
  config.vm.synced_folder "../../../facts-db/", "/vagrant-mnt/facts-db"
  config.vm.synced_folder "../../../facts-js/", "/vagrant-mnt/facts-js"
end
