Vagrant.configure("2") do |config|
  config.vm.box = "aws"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET_KEY']
    aws.region = "us-west-2"
    aws.keypair_name = "bill-boyer.com"
    aws.security_groups = ["bill-boyer.com"]
    aws.ami = "ami-986bffa8"
    aws.instance_type = "t1.micro"

    aws.tags = {
      'Name' => 'new-www.bill-boyer.com'
    }

    override.ssh.username = "root"
    override.ssh.private_key_path = ENV['AWS_PRIVATE_KEY_PATH']
  end

  config.vm.provision :shell do |s|
    s.path = "provision"
  end

  config.vm.define "1", primary: true
  config.vm.define "2"
  config.vm.define "3"
  config.vm.define "4"
  config.vm.define "5"
  config.vm.define "6"
  config.vm.define "7"
  config.vm.define "8"
  config.vm.define "9"

  config.vm.synced_folder "../../src, "/vagrant-mnt/src"
  config.vm.synced_folder "../shared", "/vagrant-mnt/env-shared"
  config.vm.synced_folder "/vagrant-mnt/ops", "/vagrant-mnt/ops"
  config.vm.synced_folder "../../../facts-db/", "/vagrant-mnt/facts-db"
  config.vm.synced_folder "../../../facts-js/", "/vagrant-mnt/facts-js"
end
