#!/bin/bash --noprofile

if [ ! -d "/vagrant-mnt/ops/scripts" ];
then
   echo "This script must only be run from the ops instance."
   exit 1
fi

if [ $# -ne 1 ] ;
then
	echo "Usage: deploy-all <recycle>"
	exit 1
fi

/vagrant-mnt/ops/scripts/infrastructure/aws/cycle-machines www.bill-boyer.com www-bill-boyer-com $1 1 1
