#!/bin/bash

if [ $# != 2 ] ;
then
	echo "Usage: provision <env> <hostname>"
	exit 1
fi

env=$1
hostname=$2

ops=/vagrant-mnt/ops/scripts
path=$ops/provision/ubuntu

$path/base $ops
$path/prompt www.bill-boyer.com $env
$path/git
$path/apache
$path/php
$path/wordpress
$path/node
$path/ruby
$path/rails
$path/sqlite
$path/sqlite-php
$path/passenger www.bill-boyer.com
$path/mongodb
$path/grunt
$path/compass

cat > /etc/apache2/sites-available/default <<EOF
<VirtualHost *:80>
  ServerName *.bill-boyer.com
  ServerAlias *.compute.amazonaws.com

  DocumentRoot /srv/www/docroot
  <Directory /srv/www/docroot/>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
  </Directory>

  Alias /js /srv/www/dist/js
  Alias /css /srv/www/dist/css
  Alias /dist /srv/www/dist
  Alias /blog /srv/wordpress

  ProxyPass /js !
  ProxyPass /css !
  ProxyPass /img !
  ProxyPass /dist !
  ProxyPass /blog !
  ProxyPass /test/php !
  ProxyPass /test/html !
  ProxyPass /favicon.ico !
  ProxyPass /googleb3e16bb506c5133e.html !

  ProxyPass /api http://localhost:3000

  ProxyPass /test/rails http://localhost:81/rails
  ProxyPass / http://localhost:81/

  ErrorLog /var/log/apache2/error.log
  LogLevel warn
  CustomLog /var/log/apache2/access.log combined
</VirtualHost>

<VirtualHost *:80>
  ServerName bill-boyer.com
  ServerAlias william-boyer.com *.william-boyer.com boyer.nyc *.boyer.nyc
  Redirect permanent / http://www.bill-boyer.com/
</VirtualHost>
EOF

service apache2 restart

curl http://localhost/blog/

/vagrant-mnt/env/shared/load-latest-databases $hostname

cd /srv/www
rm -rf dist
mkdir dist

rm -rf /srv/node
mkdir -p /srv/node
cd /srv/node
mkdir dist

cp /vagrant-mnt/env/shared/package.json .
npm install
sleep 30
npm install
sleep 30
npm install

cp /vagrant-mnt/env/shared/bower.json .
cp /vagrant-mnt/env/shared/.bowerrc .
./node_modules/bower/bin/bower --allow-root install

cat > /etc/init/node-js.conf <<EOF

start on started mountall
stop on shutdown

respawn
respawn limit 99 5

script
    export NODE_PATH=$NODE_PATH:/srv/node/node_modules
    exec /usr/bin/node /srv/node/dist/main.min.js >> /var/log/node.log 2>&1
end script

EOF

service node-js restart
