#!/bin/bash

if [ $# -ne 2 ] ;
then
	echo "Usage: release <facts-db tag> <fact-js tag>"
	exit 1
fi

curl -s -L https://github.com/wboyer/facts-db/archive/v$1.tar.gz | gunzip | tar xf -
mv facts-db-$1 facts-db

curl -s -L https://github.com/wboyer/facts-js/archive/v$2.tar.gz | gunzip | tar xf -
mv facts-js-$2 facts-js

mkdir -p build
cd build

cp ../env/shared/Gruntfile.js .
cp ../facts-db/package.json .
npm install

grunt build --src=.. --www-dest=../dist/www --node-dest=../dist/node

# test
# publish to artifact repository
