#!/bin/bash

mkdir -p build
cd build

cp ../env/shared/package.json .
npm install

cp ../env/shared/bower.json .
cp ../env/shared/.bowerrc .
./node_modules/bower/bin/bower --allow-root install

cp ../env/shared/Gruntfile.js .
grunt build --src=.. --dest=../dist

# test
# publish to artifact repository
