#!/bin/bash

mkdir -p build/node
cd build/node

cp ../../env/shared/package.json .
npm install

cp ../../env/shared/bower.json .
cp ../../env/shared/.bowerrc .
./node_modules/bower/bin/bower --allow-root install

mkdir -p ../rails
mkdir -p ../wordpress/wp-content/themes/blog.bill-boyer.com

cp ../../env/shared/Gruntfile.js .
grunt copy-build --src=../.. --dest=..

# test
# publish to artifact repository
